export const CURRENT_REQUEST = "CURRENT_REQUEST";
export const ONECALL_REQUEST = "ONECALL_REQUEST";
export const SEARCH_TERM = "SEARCH_TERM";
export const CHANGE_UNITS = "CHANGE_UNITS";
export const TOGGLE_THEME = "TOGGLE_THEME";
export const RESET_CURRENT = "RESET_CURRENT";
export const RESET_ONECALL = "RESET_ONECALL";
export const RESET_SEARCH_TERM = "RESET_SEARCH_TERM";
